version: '3.9'

services:
  postgres:
    container_name: matsuhub-local-postgres
    build: docker/postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

volumes:
  pgdata:
    name: pgdata
